substitutions:
  system_name: display-01
  friendly_name: "Display-01"  
  device_description: "TTGO - ESP32 Display"

packages:
  device: !include devices/ttgo-t1.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_12
    size: 12

sensor:
  - platform: homeassistant
    id: tent_temperature
    name: "Tent Temperature"
    entity_id: sensor.tent_temperature_2
    state_class: measurement
    unit_of_measurement: °F
    device_class: temperature
    internal: true
    
  - platform: homeassistant
    id: tent_humidity
    name: "Tent Humidity"
    entity_id: sensor.tent_humidity_2
    state_class: measurement
    unit_of_measurement: '%'
    device_class: humidity
    internal: true
    
binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1

# We can still control the backlight independently
switch:
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight

image:
  - file: "images/image.png"
    id: my_image
    resize: 200x200
    type: RGB24

time:
  - platform: homeassistant
    id: esptime

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 270
    lambda: |-
      // Draw Border
      it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_blue));
      it.rectangle(0, 20, it.get_width(), it.get_height(), id(my_blue));   // header bar

      // ESPHome Name
      it.print(5, 5, id(helvetica_12), id(my_yellow), TextAlign::TOP_LEFT, "Display-01:");
      
      // Temp & Humidity
      it.printf(55, 35, id(helvetica_24), id(my_gray), TextAlign::CENTER, "Temp: %.0f°", id(tent_temperature).state);
      it.printf(55, 55, id(helvetica_24), id(my_gray), TextAlign::CENTER, "Humd: %.0f°", id(tent_humidity).state);

      // ESPHome Status
       if (id(system_status).state) {
        it.print(235, 5, id(helvetica_12), id(my_green), TextAlign::TOP_RIGHT, "Online");
      }
      else {
        it.print(235, 5, id(helvetica_12), id(my_red), TextAlign::TOP_RIGHT, "Offline");
      }
