esphome:
  name: lux
  includes:
    - include/veml7700_custom_sensor.h
  libraries:
    - Wire
    - SPI
    - AdaFruit/Adafruit BusIO @ 1.10.1
    - AdaFruit VEML7700=https://github.com/adafruit/Adafruit_VEML7700

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "3ee9ead5f7bf3c4c5821b787026e92d6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lux Fallback Hotspot"
    password: "DFQ0U889piGY"

captive_portal:

web_server:
  id: component_web_server
  port: 80

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: true

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
    humidity:
      name: "Relative Humidity"

  - platform: custom
    lambda: |-
      auto veml7700 = new VEML7700CustomSensor();
      App.register_component(veml7700);
      return {veml7700, veml7700->lux_sensor, veml7700->white_sensor, veml7700->als_sensor};
    sensors:
    - name: "VEML7700 Light" # Required dummy sensor
    - name: "VEML770 Lux"
      accuracy_decimals: 1
      unit_of_measurement: Lux
    - name: "VEML770 White"
      unit_of_measurement: Lux
      accuracy_decimals: 0
    - name: "VEML770 ALS"
      unit_of_measurement: Lux
      accuracy_decimals: 0
